# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrarProyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('listar_todos_los_proyectos', 'listar los proyectos disponibles'), ('listar_proyectos_de_usuario', 'listar los proyectos de un usuario'), ('ver_proyecto', 'ver el proyecto'), ('aprobar_proyecto', 'aprobar el proyecto'), ('asignar_scrum_master', 'asignar scrum master al equipo'))},
        ),
    ]
