# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta')], default=0),
        ),
    ]
