# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('listar_proyectos', 'Listar todos los proyectos disponibles'), ('listar_proyectos_usuario', 'Listar todos los proyectos de un Usuario'), ('ver_proyecto', 'ver detalles del proyecto'), ('asignar_equipo', 'asignar los miembros del equipo'), ('aprobar_proyecto', 'permiso para aprobar el proyecto'))},
        ),
    ]
