# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 14, 17, 14, 20466)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 14, 17, 14, 20439)),
        ),
    ]
