# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_userstory_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('listar_proyectos', 'Listar Proyectos'), ('ver_proyecto', 'Ver detalles del proyecto'), ('asignar_equipo', 'Asignar los miembros del equipo'), ('aprobar_proyecto', 'Aprobar el proyecto'), ('crear_sprint', 'Agregar Sprint'), ('editar_sprint', 'Editar Sprint'), ('eliminar_sprint', 'Eliminar Sprint'), ('ver_sprint', 'Ver Sprint'), ('crear_flujo', 'Agregar Flujo'), ('editar_flujo', 'Editar Flujo'), ('eliminar_flujo', 'Eliminar Flujo'), ('ver_flujo', 'Ver Flujo'), ('crear_userstory', 'Agregar User Story'), ('editar_userstory', 'Editar User Story'), ('eliminar_userstory', 'Eliminar User Story'), ('registraractividad_userstory', 'Registrar avances en User Story'), ('aprobar_userstory', 'Aprobar User Story completado'), ('cancelar_userstory', 'Cancelar User Story completado'), ('priorizar_userstory', 'asignar prioridad a userstories'))},
        ),
    ]
