# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20160526_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='prioridadFormula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
