# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20160511_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('listar_proyectos', 'Listar todos los proyectos disponibles'), ('listar_proyectos_usuario', 'Listar todos los proyectos de un Usuario'), ('ver_proyecto', 'ver detalles del proyecto'), ('asignar_equipo', 'asignar los miembros del equipo'), ('aprobar_proyecto', 'aprobar el proyecto'), ('crear_sprint', 'agregar sprint'), ('editar_sprint', 'editar sprint'), ('eliminar_sprint', 'eliminar sprint'), ('crear_flujo', 'agregar flujo'), ('editar_flujo', 'editar flujo'), ('eliminar_flujo', 'eliminar flujo'))},
        ),
    ]
