# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_userstory_prioridadformula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridadFormula',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
