# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0005_auto_20160511_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('filename', models.CharField(editable=False, max_length=100, null=True)),
                ('binario', models.BinaryField(blank=True, null=True)),
                ('content_type', models.CharField(editable=False, max_length=50, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('img', 'Imagen'), ('text', 'Texto'), ('misc', 'Otro'), ('src', 'Codigo')], default='misc', max_length=10)),
                ('lenguaje', models.CharField(choices=[('clike', 'C'), ('python', 'Python'), ('ruby', 'Ruby'), ('css', 'CSS'), ('php', 'PHP'), ('scala', 'Scala'), ('sql', 'SQL'), ('bash', 'Bash'), ('javascript', 'JavaScript'), ('markup', 'Markup')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje de descripcion de los avances o motivo de cancelacion', null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_registrado', models.IntegerField(default=0)),
                ('horas_a_registrar', models.IntegerField(default=0)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'En curso'), (2, 'Pendiente Aprobacion'), (3, 'Aprobado'), (4, 'Cancelado')], default=0)),
                ('estado_actividad', models.IntegerField(choices=[(0, 'ToDo'), (1, 'Doing'), (2, 'Done')], null=True)),
                ('desarrollador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta')], default=0)),
                ('valor_negocio', models.IntegerField()),
                ('valor_tecnico', models.IntegerField()),
                ('tiempo_estimado', models.PositiveIntegerField()),
                ('tiempo_registrado', models.PositiveIntegerField(default=0)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'En curso'), (2, 'Pendiente Aprobacion'), (3, 'Aprobado'), (4, 'Cancelado')], default=0)),
                ('estado_actividad', models.IntegerField(choices=[(0, 'ToDo'), (1, 'Doing'), (2, 'Done')], default=0)),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Proyecto')),
            ],
            options={
                'verbose_name_plural': 'user stories',
                'permissions': (('edit_my_userstory', 'editar mis userstories'), ('registraractividad_my_userstory', 'registrar avances en mis userstories')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.UserStory'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.UserStory'),
        ),
    ]
