# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 22:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0005_auto_20160511_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('filename', models.CharField(editable=False, max_length=100, null=True)),
                ('binario', models.BinaryField(blank=True, null=True)),
                ('content_type', models.CharField(editable=False, max_length=50, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('img', 'Imagen'), ('text', 'Texto'), ('misc', 'Otro'), ('src', 'Codigo')], default='misc', max_length=10)),
                ('lenguaje', models.CharField(choices=[('clike', 'C'), ('python', 'Python'), ('ruby', 'Ruby'), ('css', 'CSS'), ('php', 'PHP'), ('scala', 'Scala'), ('sql', 'SQL'), ('bash', 'Bash'), ('javascript', 'JavaScript'), ('markup', 'Markup')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=20)),
                ('nombre_largo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('valor_negocio', models.IntegerField()),
                ('valor_tecnico', models.IntegerField()),
                ('tiempo_estimado', models.PositiveIntegerField()),
                ('tiempo_registrado', models.PositiveIntegerField(default=0)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'En curso'), (2, 'Pendiente Aprobacion'), (3, 'Aprobado'), (4, 'Cancelado')], default=0)),
                ('estado_actividad', models.IntegerField(choices=[(0, 'ToDo'), (1, 'Doing'), (2, 'Done')], default=0)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Actividad')),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user stories',
                'permissions': (('editar_mi_userstory', 'editar mis userstories'), ('registraractividad_mi_userstory', 'registrar avances en mis userstories')),
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('listar_proyectos', 'Listar todos los proyectos disponibles'), ('listar_proyectos_usuario', 'Listar todos los proyectos de un Usuario'), ('ver_proyecto', 'ver detalles del proyecto'), ('asignar_equipo', 'asignar los miembros del equipo'), ('aprobar_proyecto', 'aprobar el proyecto'), ('crear_sprint', 'agregar sprint'), ('editar_sprint', 'editar sprint'), ('eliminar_sprint', 'eliminar sprint'), ('crear_flujo', 'agregar flujo'), ('editar_flujo', 'editar flujo'), ('eliminar_flujo', 'eliminar flujo'), ('crear_userstory', 'agregar userstory'), ('editar_userstory', 'editar userstory'), ('eliminar_userstory', 'eliminar userstory'), ('registraractividad_userstory', 'registrar avances en userstories'), ('aprobar_userstory', 'aprobar userstories completados'), ('cancelar_userstory', 'cancela userstories completados'))},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 18, 48, 28, 1478)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 18, 48, 28, 1460)),
        ),
        migrations.AddField(
            model_name='userstory',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Proyecto'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Sprint'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.UserStory'),
        ),
    ]
