# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20160516_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 11, 25, 15, 308893)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 11, 25, 15, 308865)),
        ),
    ]
