# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 22:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20160513_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 18, 51, 18, 481556)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 18, 51, 18, 481539)),
        ),
    ]
